storeDir = "~/code/dotfiles"

after-backup = []

[backup.bashrc]
location = "~/.bashrc"

[backup.alacritty]
location = "~/.config/alacritty"

[backup.dotback]
location = "~/.config/dotback"

[backup.ghostty]
location = "~/.config/ghostty"



