#!/bin/sh
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#

# If you want to use GNOME config tools...
#
#if test -x /usr/lib/openbox/gnome-settings-daemon >/dev/null; then
#  /usr/lib/openbox/gnome-settings-daemon &
#elif which gnome-settings-daemon >/dev/null 2>&1; then
#  gnome-settings-daemon &
#fi

# If you want to use XFCE config tools...
#
#xfce-mcs-manager &

picom -b &
feh --no-fehbg --bg-scale ~/.config/wallpaper/wallpaper.png &
alacritty &
emacs --daemon
killall transmission-daemon; transmission-daemon &
xss-lock slock &
killall mpd ; mpd &
dunst &
unclutter &
setxkbmap -option ctrl:nocaps &
xmobar ~/.config/xmobar/xmobarrc-openbox
pytyle1x
